spring.application.name=clean-spring-boot-project
# ===============================
# = ИСТОЧНИК ДАННЫХ
# ===============================
# Настройки подключения к базе данных
spring.datasource.url=jdbc:postgresql://localhost:5432/yourdatabase
spring.datasource.username=postgres
spring.datasource.password=postgres_password
spring.datasource.driver-class-name=org.postgresql.Driver
# Поддерживать соединение активным при длительном простое (необходимо в production)
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================
# Показывать или нет SQL-запросы в логах
spring.jpa.show-sql=true
# Автоматическое управление схемой БД (create, create-drop, update): при "create-drop"
# схема БД будет автоматически создана заново при каждом запуске приложения
# spring.jpa.hibernate.ddl-auto=create-drop

# Заставить Hibernate генерировать SQL, оптимизированный для конкретной СУБД
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = БЕЗОПАСНОСТЬ
# ===============================

# Секретный ключ JWT
auth.security.token.secret=${JWT_SECRET:secret-key}
# Время жизни JWT-токена в секундах, по умолчанию 2 часа
auth.security.token.expiration-time=${JWT_EXPIRATION_TIME:7200}

# ===============================
# = EMAIL
# ===============================
# MailHog SMTP (для локальной разработки)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=mailhog
spring.mail.password=mailhog
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false 
